### ISSUE TITLE
Error when adding all shared parts to new env

### ISSUE THREAD

**Issue by Snakefin** [silverfin/silverfin-cli#97]
When running the command 'silverfin add-shared-part --all --yes'
got this: 

` ERROR  Cannot read properties of undefined (reading 'status')                                                                                                                                                   8:39:40 AM

silverfin: v1.25.1, node: v19.4.0

TypeError: Cannot read properties of undefined (reading 'status')
    at Object.responseErrorHandler (/opt/homebrew/lib/node_modules/silverfin-cli/lib/utils/apiUtils.js:117:22)
    at addSharedPartToReconciliation (/opt/homebrew/lib/node_modules/silverfin-cli/lib/api/sfApi.js:436:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async addSharedPart (/opt/homebrew/lib/node_modules/silverfin-cli/index.js:633:20)`

**Comment by Snakefin** [comment]
To be clear, the CLI said to post it here, together with the log... 

Some background info: created a new env, created all RT's and shared parts. Later on, fetched all ID's, and tried to add shared parts to all RT's
